### ISSUE TITLE
String processing demo ideas

### ISSUE THREAD

**Issue by robguderian** [robguderian/cs-tech-primer#3]
* Hash table
* search and replace
* longest subsequence, substring

Or, should we do something else?

We'll talk about this on our first meeting

**Comment by smigii** [comment]
Just an idea, in 2160 we wrote a Levenshtein distance program. Kind of string process-y, but maybe more confusing than the other options.

**Comment by robguderian** [comment]
* substring
* search
* index a letter
* split?
* Palindromicity

Book summary is best for this? Rockyou corpus

* how many passwords have the word 'pass' in it?
* see if you've been owned
* count letter frequencies
* .... we'll probably just use this
* how many palindromes are there in the corpus
